/**
 * Canonical agent rules content — hand-tuned, do not generate programmatically.
 *
 * Operating manual for agents working in a Yggdrasil-managed repository.
 */
// prettier-ignore
export const AGENT_RULES_CONTENT = `# Yggdrasil — Operating Manual

You are working in a repository managed by Yggdrasil. Yggdrasil is persistent semantic memory stored in \`.yggdrasil/\`. It maps the repository and provides deterministic implementation context for every node.

**Why it exists:** AI agents degrade with project size. Too little context breaks contracts. Too much context buries signal in noise. The graph gives agents exactly the right context — not the whole repository. A repository with Yggdrasil is self-aware: it knows what it is, what it must satisfy, and why decisions were made.

THIS DOCUMENT IS YOUR COMPLETE OPERATING MANUAL. Read it fully. Follow it strictly.

---

## 0. ATOMIC INVARIANT — OVERRIDES EVERYTHING

**CODE ↔ GRAPH ARE ONE.**

- Code changed → graph artifacts MUST be updated IN THE SAME RESPONSE. No exceptions.
- Graph changed → source files MUST be verified or updated IN THE SAME RESPONSE. No exceptions.
- There is NO "code-only" response. There is NO "graph-only" response (unless explicitly a dry-run plan).
- Completing a response with one side changed and the other untouched violates the core contract of Yggdrasil.

---

## 1. GRAPH STRUCTURE

The graph lives in \`.yggdrasil/\` and has three semantic directories plus configuration:

\`\`\`
.yggdrasil/
  config.yaml        ← vocabulary, stack, node types, artifact rules, required aspects per type
  model/             ← what exists: nodes, hierarchy, relations, file mappings
  aspects/           ← what must: cross-cutting requirements with rationale and guidance
  flows/             ← why and in what process: business processes with node participation
  templates/         ← YAML schemas — read before creating any graph element
  .drift-state       ← generated by CLI; never edit manually
  .journal.yaml      ← generated by CLI; never edit manually
\`\`\`

### model/ — What exists

Each node is a directory containing \`node.yaml\` and artifact files. Nodes nest to form a hierarchy — a parent node provides domain context to all its descendants.

\`\`\`
model/
  orders/                        ← module node (parent)
    node.yaml
    responsibility.md
    order-service/               ← leaf node
      node.yaml
      responsibility.md
      interface.md
      constraints.md
      errors.md
\`\`\`

Children do not repeat context that belongs to a parent — the engine assembles the full hierarchy automatically during context assembly.

### aspects/ — What must

Each aspect is a directory with the following files:

\`\`\`
aspects/
  requires-audit/
    aspect.yaml       ← name (display), optional implies. Tag = directory name.
    requirement.md    ← WHAT must be satisfied (specific and verifiable)
    rationale.md      ← WHY this requirement exists (traceability)
    guidance.md       ← HOW to satisfy it — optional, may include code examples
\`\`\`

**Tag = directory name.** Each aspect lives in \`aspects/<tag>/\` (e.g. \`aspects/requires-audit/\`).
Run \`yg tags\` to list valid tags.

### flows/ — Why and in what process

Each flow is a directory with the following files:

\`\`\`
flows/
  customer-checkout/
    flow.yaml         ← nodes (paths in model/), aspects (tags propagated to participants)
    description.md    ← business-first process description
\`\`\`

Flows describe real business processes in which the software participates. A flow exists because there is a human or organizational process behind it. The software is a tool in that process — not the process itself. A flow description that describes only code sequences is wrong.

**Required sections in every \`description.md\`:**
- \`## Business context\` — what organizational or user need this process serves
- \`## Trigger\` — what initiates this process (user action, external event, schedule)
- \`## Goal\` — what successful completion means from the business perspective
- \`## Participants\` — which nodes participate and what role each plays
- \`## Paths\` — happy path and other business paths with error handling and edge cases

**Flow aspects:** aspects declared in \`flow.yaml\` propagate to all participants:

\`\`\`yaml
nodes:
  - orders/order-service
  - payments/payment-service
aspects:
  - requires-saga
  - requires-idempotency
\`\`\`

Every participant receives these aspects in its context package even if the node itself does not carry the tag.

---

## 2. CONTEXT ASSEMBLY

\`yg build-context --node <path>\` assembles a deterministic context package in this order:

\`\`\`
1. WORLD IDENTITY     config.yaml: stack, standards
2. HIERARCHY          artifacts of all ancestor nodes from root down to this node's parent.
                      Each hierarchy block may have aspects="tag1,tag2" (omit if empty).
3. OWN ARTIFACTS      this node's node.yaml and all its artifact files.
                      Node may have tags (aspects) in node.yaml.
4. ASPECTS            union of tags from hierarchy + own + flow blocks. Each block declares
                      its own — no inheritance. Expand implies recursively. Render content.
5. DEPENDENCIES       structural-context artifacts of each node this node depends on:
                      responsibility, interface, constraints, errors
                      + consumes and failure annotations from the relation declaration
6. FLOWS              description.md of each flow listing this node as participant.
                      Flow blocks may have aspects propagated to participants.
\`\`\`

The package is bounded — it contains exactly what is relevant to this node and nothing more. If a context package is insufficient for an agent to implement a node correctly, the graph is incomplete. The fix is always on the graph side, never by exploring raw source files.

---

## 3. CORE PRINCIPLES

1. **Graph first.** Before modifying code, before answering questions about mapped files, before planning — run \`yg owner\` and \`yg build-context\`. Always.

2. **Context is sufficient.** If you feel the need to explore source files to understand what a node should do, the context package is incomplete. Enrich the graph. Do not bypass it.

3. **Graph is intended truth.** When code and graph diverge, the graph wins. If the divergence is deliberate, update the graph to match the code.

4. **Exhaustive coverage.** Every source file belongs to exactly one node. No orphaned files.

5. **Never invent why.** The graph captures human intent. If you do not know why something was decided, ask the user. Never hallucinate rationale, business rules, or architectural decisions.

6. **Always capture why.** When the user explains a reason, a constraint, or a decision — record it in the graph immediately. Conversation context evaporates. Graph context persists.

7. **Ask before resolving ambiguity.** When code and graph diverge with multiple valid interpretations, or when a required decision is unclear — stop, list the options, ask the user. Never silently choose.

8. **English only for graph artifacts.** All files in \`.yggdrasil/\` must be written in English. Conversation can be in any language.

9. **Never touch operational metadata.** Never manually edit \`.drift-state\`, \`.index\`, or \`.journal.yaml\`.

10. **Read templates before creating.** Before creating or editing any \`node.yaml\`, \`aspect.yaml\`, or \`flow.yaml\` — read the corresponding schema in \`templates/\`.

---

## 4. FAILURE STATES

You have broken Yggdrasil if you do any of the following:

- ❌ Modified source code without running \`yg owner --file <path>\` first.
- ❌ Modified source code without updating graph artifacts in the same response.
- ❌ Modified graph files without verifying source code alignment in the same response.
- ❌ Resolved a code↔graph inconsistency without asking the user first.
- ❌ Created or edited a graph element without reading its schema in \`templates/\`.
- ❌ Ran \`yg drift-sync\` before updating graph artifacts.
- ❌ Ran \`yg drift-sync\` for specification drift without explicit user acknowledgment.
- ❌ Re-materialized a node after a specification drift alert without showing the user the component diff first.
- ❌ Wrote a flow description that describes code sequences instead of a business process.
- ❌ Used a tag that has no \`aspects/<tag>/\` directory (run \`yg tags\` to list valid tags).
- ❌ Placed a cross-cutting requirement in a local node artifact instead of an aspect.
- ❌ Invented a rationale, business rule, or architectural decision.
- ❌ Used blackbox coverage for greenfield (new) code.
- ❌ Answered a question about a mapped file without running \`yg build-context\` first.

---

## 5. WORKFLOW — MODIFYING OR CREATING SOURCE CODE

You are not allowed to edit or create source code without establishing graph coverage first.

### Step 1 — Check coverage

\`\`\`
yg owner --file <path>
\`\`\`

### Step 2a — Owner found: execute checklist

Output this checklist in your response and complete every item before finishing your turn:

- [ ] 1. Read specification: \`yg build-context --node <node_path>\`
- [ ] 2. Modify source code
- [ ] 3. Sync graph artifacts — edit artifact files to reflect the changes immediately
- [ ] 4. Run \`yg validate\` — fix all errors before proceeding
- [ ] 5. Run \`yg drift-sync --node <node_path>\` — only after graph and code are both current

### Step 2b — Owner not found: establish coverage first

Present the options to the user. Do not proceed until they choose.

**If existing code:**
- Option A — Full node: create proper node(s), map files, write artifacts from code analysis
- Option B — Blackbox: create a blackbox node at agreed granularity
- Option C — Abort

**If greenfield (new code):**
- Only Option A is valid. Blackbox is forbidden for new code.
- Create nodes with full artifacts representing the intended design, then materialize.

After the user chooses, return to Step 1 and follow Step 2a.

---

## 6. WORKFLOW — MODIFYING THE GRAPH

When creating or editing graph elements:

1. Read the relevant schema from \`templates/\` before touching any YAML.
2. Make changes.
3. Run \`yg validate\` immediately. Fix all errors.
4. Verify that affected source files are consistent. Update if needed.
5. Run \`yg drift-sync\` for affected nodes.

---

## 7. ROUTING — WHERE DOES INFORMATION GO?

When you encounter information during mapping or conversation, use these rules to place it:

### Is it true only for this specific node?
→ **Local node artifact.** Read \`config.yaml artifacts\` to know which files are defined and what each captures. Use only configured artifact types — do not invent filenames.

### Is it a rule that applies to many nodes of the same type or tag?
→ **Aspect.** Run \`yg tags\` to see existing aspects. If an aspect exists — add the tag to the node. If no — create \`aspects/<tag>/\` with \`aspect.yaml\`, \`requirement.md\`, \`rationale.md\`, and optionally \`guidance.md\`. Then tag the node.

If the rule applies to ALL nodes of a type — add it to \`node_types[*].required_tags\` in \`config.yaml\` (if supported). It will apply automatically without per-node tagging.

### Is it a business process this node participates in?
→ **Flow.** Check if a flow for this process exists. If yes — add the node to \`flow.yaml participants\`. If no — create the flow directory, write \`description.md\` with all four required sections. Ask the user to describe the business process if you cannot determine it from code alone.

### Is it shared context for all nodes in a domain?
→ **Parent node artifact.** Place it in the parent module node. Children receive it through hierarchy. Do not repeat it in child nodes. For cross-cutting requirements shared by the whole module, add the tag to the parent's \`node.yaml\` — descendants receive that aspect in the hierarchy block during context assembly.

### Is it a technology stack choice or global coding standard?
→ **\`config.yaml\`** under \`stack\` or \`standards\`. For technology choices, add a \`<field>_rationale\` sibling key recording the reason.

### Decision routing
When the user explains WHY something was decided:

- Applies to one node → record in that node's \`decisions.md\`.
- Applies to a category of nodes → record in the relevant aspect's \`rationale.md\`. The rationale field is the decision record for that aspect.
- Technology choice → record in \`config.yaml\` with a \`rationale\` field next to the technology declaration.

---

## 8. ASPECTS — CREATION AND USE

### Creating a new aspect

1. Read \`templates/aspect.yaml\`.
2. Create \`aspects/<tag>/\` directory (tag = directory name).
3. Write \`aspect.yaml\` — name (display), optional implies. No \`tag\` field — directory name is the tag.
4. Write \`requirement.md\` — what must be satisfied. Be specific and verifiable.
5. Write \`rationale.md\` — why this requirement exists. Use the user's own words when they provided the reason. Do not paraphrase or invent.
6. Write \`guidance.md\` — only if there is concrete implementation guidance to record. May include code examples. Omit if not needed.
7. Run \`yg validate\`.

### Aspect vs local artifact — the test

"Does this requirement apply to more than one node?"
- Yes → aspect.
- No → local artifact.

"Does this requirement apply to every node of a given type?"
- Yes → add to \`node_types[*].required_tags\` in \`config.yaml\` (if supported).
- No → optional aspect via tag on node.

---

## 9. FLOWS — CREATION AND USE

### Creating a new flow

1. Read \`templates/flow.yaml\`.
2. Create \`flows/<name>/\` directory.
3. Write \`flow.yaml\` — declare participants and any flow-level aspects.
4. Write \`description.md\` with all four required sections:

\`\`\`markdown
## Business context
[The organizational or user need this process serves. Why it exists in the business.]

## Trigger
[What initiates this process — a user action, an external event, a scheduled job. Described at the level of the actor, not the system.]

## Goal
[What successful completion looks like from the business perspective. Not a technical outcome — a business outcome.]

## Participants
[Each node and its role in the process. One to two sentences per node.]
\`\`\`

5. Run \`yg validate\`.

### Flow description — the test

Read your \`description.md\` and ask: "Does this describe what happens in the world, or only what happens in the software?" If the answer is "only in the software" — rewrite. The flow describes the process. The software is one implementation of that process.

---

## 10. REVERSE ENGINEERING — MAPPING EXISTING CODE

When mapping existing source files to graph nodes:

1. \`yg owner --file <path>\` — confirm no coverage exists.
2. Determine node granularity. Propose to user if unclear.
3. Create node directory. Read \`templates/node.yaml\`. Create \`node.yaml\`.
4. Analyze source. For each artifact type in \`config.artifacts\`: Does this node have content matching this artifact's description? Yes → create the artifact, extract content from source. Do not invent. No → skip.
5. Identify relations — what does this code call, use, extend, implement? Add relations to \`node.yaml\`.
6. Identify cross-cutting requirements — logging, auth, retry, saga, etc. Add matching tags. Create aspects if they do not exist.
7. Identify business process participation. Add the node to the relevant flow's participants. If no flow exists — ask the user to describe the business process before creating one. Do not derive a flow description from code alone.
8. Run \`yg validate\`. Fix errors.
9. Run \`yg drift-sync --node <path>\`.

### When to ask the user

Ask when:
- A node appears to participate in a business process but you cannot determine the process from code. Say: "This code appears to be part of a larger process. Can you describe what this process means from a business perspective — what triggers it and what the goal is?"
- A constraint or rule is implied by code but has no visible rationale. Say: "I see [constraint X] in the code. Do you know why this constraint exists? I want to record the reason, not just the rule."
- An architectural choice is apparent but unexplained. Say: "I see [approach X] used here. What was the reason for this choice? I want to record it so future agents understand the intent."

Do not proceed without capturing the why if the user can provide it.

---

## 11. CONVERSATION LIFECYCLE

### A. Preflight (first message of the conversation)

Always execute before doing anything else. Exception: purely read-only request (user asks only for explanation or analysis).

1. \`yg journal-read\` → if entries exist, consolidate to graph, then \`yg journal-archive\`.
2. \`yg drift\` → compares per-component hashes in \`.drift-state\` with current graph state. **Source drift** (mapped files changed) → absorb silently: \`yg drift-sync\` per node. **Specification drift** (aspect, dependency interface, flow, parent, or config changed) → do NOT absorb silently. Handle per Section 14. **Missing or unmaterialized** → report to user and ask how to proceed.
3. \`yg status\` → report graph health.
4. \`yg validate\` → report errors. Fix stale artifact warnings if present.

### B. Answering questions about mapped code

1. \`yg owner --file <path>\`
2. Owner found → \`yg build-context --node <path>\`. Base your answer on the context package.
3. Owner not found → answer from file analysis, but state explicitly that the answer is not graph-backed and graph coverage is missing.

Never answer questions about mapped code from grep or raw file reading alone. The graph provides intent, constraints, and relations that source files cannot.

### C. Wrap-up (user signals end of session)

Triggered by: "we're done", "wrap up", "that's enough", "ok done", or equivalent. The graph should already be current. Massive graph updates at this stage mean you failed to maintain sync during the session.

1. If journal was used: consolidate to graph, then \`yg journal-archive\`.
2. \`yg drift\` → absorb source drift automatically. Surface specification drift for user review.
3. \`yg validate\` → fix structural errors.
4. Report: exactly which nodes and files were changed.

---

## 12. CLI TOOLS REFERENCE

\`\`\`
yg owner --file <path>              Find the node that owns this file.
yg build-context --node <path>      Assemble context package for this node.
yg tree [--root <path>] [--depth N] Print graph structure.
yg tags                             List valid aspect tags (aspect directory names).
yg deps --node <path>               Show dependencies (structural and event).
yg impact --node <path> --simulate  Simulate blast radius of a planned change.
yg status                           Graph health: nodes, coverage, drift summary.
yg validate [--scope <path>|all]    Check structural integrity and completeness.
yg index                            Rebuild .index from current graph state.
yg drift [--scope <path>|all]       Detect divergence. Reports source drift (files changed) and specification drift (graph components changed).
yg drift-sync --node <path>         Record per-component hashes as new baseline. Run ONLY after graph and source are both current.
\`\`\`

*(Journal — iterative mode only)*
\`\`\`
yg journal-read
yg journal-add --note "<content>" [--target <node_path>]
yg journal-archive
\`\`\`

---

## 13. COMPLETENESS CHECK

Before finishing any mapping or modification, ask:

> "If I delete the source file and give another agent ONLY the output of \`yg build-context\` for this node — can they recreate the file correctly? Do they understand not just WHAT the code does, but WHY it exists and WHY it was designed this way?"

- **No** → you missed a local constraint, a relation, or failed to capture rationale.
- **Yes, but local files are bloated** → you failed to route information to aspects, flows, or parent nodes. Fix the routing.
- **Yes, but rationale is invented** → remove it and ask the user for the real reason.
- **Yes** → done.

---

## 14. SPECIFICATION DRIFT — HOW TO HANDLE

Specification drift means a component of a node's context package changed in the graph since the last \`yg drift-sync\`. The source files have not changed — the specification that governs them has. This requires human judgment, not automatic absorption.

### What \`yg drift\` reports

For each node with specification drift, the tool reports which components changed:

\`\`\`
SPECIFICATION DRIFT — orders/order-service
  [changed] aspect/requires-audit          requirement.md modified
  [changed] dependency/payments/payment-service  interface.md modified
  [clean]   aspect/no-cross-db-access
  [clean]   flow/customer-checkout
  [clean]   own_artifacts
  [clean]   config_standards
\`\`\`

### Diagnosing each change

**Dependency interface changed**
→ High impact. The contract this node calls may have changed. The implementation likely needs updating.
→ Say: "The [dependency] interface changed — specifically [what]. This node calls [method]. Does the new signature require changes here?"

**Aspect requirement changed**
→ Medium impact. The obligation this node must satisfy changed. Check whether the current implementation still satisfies the new requirement.
→ Say: "The [aspect] requirement changed — [what changed]. Does the current implementation still satisfy it, or does it need updating?"

**Aspect rationale changed**
→ Low impact. Only the explanation changed, not the requirement itself. No code change expected. Absorb automatically without asking the user.

**Flow description changed**
→ Low-to-medium impact. The business process context changed. Check whether the node's role is still accurately described in its own artifacts.
→ Say: "The [flow] description changed — [what changed]. Does this node's responsibility still reflect its role in the updated process?"

**Parent node artifact changed**
→ Medium impact. The domain context changed. Check whether child responsibilities are still consistent with the updated domain.

**Config standards changed**
→ Medium impact. Global coding conventions changed. Existing code may not conform.
→ Say: "Global standards changed — [what changed]. Should this node be updated to conform?"

### After the user decides

- **"Update the code"** → modify source files, update graph artifacts, \`yg drift-sync\`.
- **"Code is fine"** → run \`yg drift-sync\` to update the baseline without code changes.
- **"Not now"** → leave drift unresolved. It will surface again on the next \`yg drift\`.

Never run \`yg drift-sync\` for specification drift without explicit user acknowledgment.

---

## 15. QUICK ROUTING REFERENCE

| What you have | Where it goes |
|---|---|
| This node's responsibility | \`responsibility.md\` (local) |
| This node's public API | \`interface.md\` (local) |
| Validation rules specific to this node | \`constraints.md\` (local) |
| Error conditions this node produces | \`errors.md\` (local) |
| Data shapes this node owns | \`model.md\` (local) |
| State machine for this node | \`state.md\` (local) |
| Local design decision + why | \`decisions.md\` (local) |
| Rule that applies to many nodes | Aspect (\`requirement.md\` + \`rationale.md\`) |
| Architectural invariant for a node type | Required aspect in \`config.yaml node_types\` |
| Business process participation | Flow (\`flow.yaml participants\`) |
| Process-level requirement | Flow \`aspects\` + aspect directory |
| Context shared across a domain | Parent node artifact |
| Technology stack | \`config.yaml stack\` (+ \`rationale\` field) |
| Global coding standards | \`config.yaml standards\` |
`;
